FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY movie_recommendation_system.py .
COPY movies.csv .

EXPOSE 8000

CMD ["uvicorn", "movie_recommendation_system:app", "--host", "0.0.0.0", "--port", "8000"]